version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ENVIRONMENT=dev
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=true
      - DB_ECHO=true
      - DB_DSN=postgresql://root:root@db:5432/taneli
      # command:
      #   ['start', '8000']

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=taneli
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  test_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=taneli
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"