/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Large1Disc(props) {
  const mesh = useRef(null);
  useFrame(
    (state, delta) => (mesh.current.rotation.y += props.rotationSpeed / 100)
  );
  const { nodes, materials } = useGLTF("/large1disc.gltf");
  return (
    <group {...props} dispose={null} ref={mesh}>
      <mesh
        geometry={nodes.Ground003.geometry}
        material={materials.Ground}
        position={[0, -0.01, 0]}
        scale={[1.67, 0.57, 1.67]}
      />
      <group position={[0.13, -0.01, -0.65]} scale={0.23}>
        <mesh
          geometry={nodes.Sphere009.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Sphere009_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Sphere009_2.geometry}
          material={materials["Material.021"]}
        />
      </group>
      <mesh
        geometry={nodes.Bedrock003.geometry}
        material={materials.Bedrock}
        position={[0.42, 0.46, -0.12]}
        rotation={[0, 0, -Math.PI]}
        scale={[1.73, 2.33, 1.52]}
      />
      <mesh
        geometry={nodes["Grass-s008"].geometry}
        material={materials["Material.024"]}
        position={[0.49, 0.05, -0.47]}
        rotation={[1.53, -0.11, -0.38]}
        scale={0.19}
      />
      <mesh
        geometry={nodes["Grass-m010"].geometry}
        material={materials["Material.019"]}
        position={[0.03, 0.06, -0.66]}
        rotation={[Math.PI / 2, 0, -0.04]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Rock010.geometry}
        material={materials["Material.025"]}
        position={[0.47, 0, -0.31]}
        rotation={[0, -0.63, 0]}
        scale={0.19}
      />
      <group
        position={[0.58, -0.01, -0.26]}
        rotation={[0, -1.15, 0]}
        scale={0.23}
      >
        <mesh
          geometry={nodes.Sphere010.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.Sphere010_1.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Sphere010_2.geometry}
          material={materials["Material.026"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m011"].geometry}
        material={materials["Material.028"]}
        position={[-0.65, 0.06, 0.29]}
        rotation={[Math.PI / 2, 0, -0.6]}
        scale={0.23}
      />
      <group position={[-0.4, 0, -0.31]} scale={[0.15, 0.07, 0.15]}>
        <mesh geometry={nodes.Circle007.geometry} material={materials.Leaves} />
        <mesh
          geometry={nodes.Circle007_1.geometry}
          material={materials.Trunk}
        />
      </group>
      <mesh
        geometry={nodes["Grass-s009"].geometry}
        material={materials["Material.003"]}
        position={[-0.44, 0.03, -0.34]}
        rotation={[1.47, 0.06, -2.17]}
        scale={0.13}
      />
      <group position={[0.09, -0.03, -0.58]} scale={0.07}>
        <mesh
          geometry={nodes.Icosphere003.geometry}
          material={materials["Light-leave"]}
        />
        <mesh
          geometry={nodes.Icosphere003_1.geometry}
          material={materials["Light-leave-basic"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m012"].geometry}
        material={materials["Material.001"]}
        position={[-0.67, 0.06, 0.19]}
        rotation={[Math.PI / 2, 0, -2.21]}
        scale={0.18}
      />
      <group position={[-0.13, 0, 0.27]} scale={[0.14, 0.12, 0.14]}>
        <mesh geometry={nodes.Circle008.geometry} material={materials.Pine} />
        <mesh
          geometry={nodes.Circle008_1.geometry}
          material={materials.Trunk}
        />
      </group>
      <group position={[-0.01, 0, -0.33]} scale={[0.1, 0.09, 0.1]}>
        <mesh geometry={nodes.Circle009.geometry} material={materials.Pine} />
        <mesh
          geometry={nodes.Circle009_1.geometry}
          material={materials.Trunk}
        />
      </group>
      <mesh
        geometry={nodes.Rock011.geometry}
        material={materials["Material.002"]}
        position={[-0.22, 0, -0.11]}
        rotation={[-Math.PI, 1.51, -Math.PI]}
        scale={0.19}
      />
      <group
        position={[0.36, -0.01, 0.57]}
        rotation={[Math.PI, -1.44, Math.PI]}
        scale={0.23}
      >
        <mesh
          geometry={nodes.Sphere011.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Sphere011_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Sphere011_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m013"].geometry}
        material={materials["Material.006"]}
        position={[0.41, 0.06, 0.45]}
        rotation={[Math.PI / 2, 0, 0.82]}
        scale={0.3}
      />
      <mesh
        geometry={nodes["Grass-m014"].geometry}
        material={materials["Material.008"]}
        position={[0.3, 0.06, 0.52]}
        rotation={[Math.PI / 2, 0, -1.77]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Rock012.geometry}
        material={materials["Material.010"]}
        position={[0.27, 0, 0.43]}
        rotation={[-Math.PI, -0.98, -Math.PI]}
        scale={0.09}
      />
      <mesh
        geometry={nodes["Grass-s010"].geometry}
        material={materials["Material.011"]}
        position={[-0.36, 0.05, -0.06]}
        rotation={[1.5, 0.09, -2.53]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Rock013.geometry}
        material={materials["Material.012"]}
        position={[-0.09, 0, 0.61]}
        rotation={[-Math.PI, -0.98, -Math.PI]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Rock014.geometry}
        material={materials["Material.013"]}
        position={[-0.02, 0, 0.65]}
        rotation={[0, 0.99, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes["Grass-s011"].geometry}
        material={materials["Material.014"]}
        position={[-0.15, 0.03, 0.58]}
        rotation={[1.51, 0.1, -2.62]}
        scale={0.14}
      />
      <mesh
        geometry={nodes["Grass-s012"].geometry}
        material={materials["Material.015"]}
        position={[-0.08, 0.03, 0.69]}
        rotation={[1.63, 0.1, 2.6]}
        scale={0.12}
      />
      <mesh
        geometry={nodes["Grass-m015"].geometry}
        material={materials["Material.022"]}
        position={[0.01, 0.05, 0.61]}
        rotation={[Math.PI / 2, 0, 0.97]}
        scale={0.16}
      />
      <group position={[0.2, 0, -0.04]} scale={0.06}>
        <mesh
          geometry={nodes.Circle010.geometry}
          material={materials["Pine.001"]}
        />
        <mesh
          geometry={nodes.Circle010_1.geometry}
          material={materials["Trunk.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Bush5001.geometry}
        material={materials["Light-leave-basic"]}
        position={[0.32, -0.01, 0.24]}
        scale={0.12}
      />
      <group
        position={[0.51, -0.01, 0.12]}
        rotation={[3.14, -0.66, 3.14]}
        scale={0.11}
      >
        <mesh geometry={nodes.Circle011.geometry} material={materials.Leaves} />
        <mesh
          geometry={nodes.Circle011_1.geometry}
          material={materials.Trunk}
        />
      </group>
      <mesh
        geometry={nodes.Purovesi.geometry}
        material={materials.Vesi}
        position={[-0.4, 0.51, 0.22]}
        rotation={[0, -1.06, 0]}
        scale={[0.51, 6.3, -0.09]}
      />
      <mesh
        geometry={nodes["Grass-s013"].geometry}
        material={materials["Material.031"]}
        position={[0.55, 0.05, -0.38]}
        rotation={[1.59, -0.12, 0.15]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Rock015.geometry}
        material={materials["Material.023"]}
        position={[-0.64, 0, -0.09]}
        rotation={[-Math.PI, -0.77, -Math.PI]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Rock016.geometry}
        material={materials["Material.030"]}
        position={[-0.58, 0, -0.04]}
        rotation={[0, 0.77, 0]}
        scale={0.09}
      />
      <group position={[-0.3, 0, -0.59]} rotation={[0, 0.97, 0]} scale={0.19}>
        <mesh
          geometry={nodes.Sphere012.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          geometry={nodes.Sphere012_1.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          geometry={nodes.Sphere012_2.geometry}
          material={materials["Material.032"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m016"].geometry}
        material={materials["Material.034"]}
        position={[-0.34, 0.06, -0.53]}
        rotation={[Math.PI / 2, 0, -1.01]}
        scale={0.24}
      />
      <group
        position={[-0.45, 0, -0.49]}
        rotation={[-Math.PI, 0.6, -Math.PI]}
        scale={0.19}
      >
        <mesh
          geometry={nodes.Sphere013.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          geometry={nodes.Sphere013_1.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          geometry={nodes.Sphere013_2.geometry}
          material={materials["Material.038"]}
        />
      </group>
      <group
        position={[-0.41, 0, -0.58]}
        rotation={[-Math.PI, 1.1, -Math.PI]}
        scale={0.13}
      >
        <mesh
          geometry={nodes.Sphere014.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          geometry={nodes.Sphere014_1.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          geometry={nodes.Sphere014_2.geometry}
          material={materials["Material.041"]}
        />
      </group>
      <group position={[0.01, -0.03, -0.05]} scale={0.07}>
        <mesh
          geometry={nodes.Icosphere005.geometry}
          material={materials["Light-leave.001"]}
        />
        <mesh
          geometry={nodes.Icosphere005_1.geometry}
          material={materials["Light-leave-basic.001"]}
        />
      </group>
      <group position={[0.09, -0.03, -0.58]} scale={0.07}>
        <mesh
          geometry={nodes.Icosphere006.geometry}
          material={materials["Light-leave.002"]}
        />
        <mesh
          geometry={nodes.Icosphere006_1.geometry}
          material={materials["Light-leave-basic.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Rock018.geometry}
        material={materials["Material.043"]}
        position={[0.37, 0, -0.22]}
        rotation={[0, -0.13, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Rock017.geometry}
        material={materials["Material.042"]}
        position={[0.47, 0, -0.18]}
        rotation={[0, 0.54, 0]}
        scale={0.09}
      />
    </group>
  );
}

useGLTF.preload("/large1disc.gltf");
