/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Medium1Disc(props) {
  const mesh = useRef(null);
  useFrame(
    (state, delta) => (mesh.current.rotation.y += props.rotationSpeed / 100)
  );
  const { nodes, materials } = useGLTF("/medium1disc.gltf");
  return (
    <group {...props} dispose={null} ref={mesh}>
      <mesh
        geometry={nodes.Ground001.geometry}
        material={materials.Ground}
        position={[0, -0.01, 0]}
        scale={[1.67, 0.57, 1.67]}
      />
      <group position={[0.21, 0, -0.49]} scale={0.44}>
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Sphere001_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Sphere001_2.geometry}
          material={materials["Material.021"]}
        />
      </group>
      <mesh
        geometry={nodes.Bedrock001.geometry}
        material={materials.Bedrock}
        position={[0.42, 0.46, -0.12]}
        rotation={[0, 0, -Math.PI]}
        scale={[1.73, 2.33, 1.52]}
      />
      <mesh
        geometry={nodes["Grass-s001"].geometry}
        material={materials["Material.024"]}
        position={[0.35, 0.1, -0.28]}
        rotation={[1.53, -0.11, -0.38]}
        scale={0.33}
      />
      <mesh
        geometry={nodes["Grass-m001"].geometry}
        material={materials["Material.019"]}
        position={[0.03, 0.12, -0.51]}
        rotation={[Math.PI / 2, 0, -0.04]}
        scale={0.51}
      />
      <mesh
        geometry={nodes.Rock001.geometry}
        material={materials["Material.025"]}
        position={[0.31, 0, 0]}
        rotation={[0, -0.63, 0]}
        scale={0.37}
      />
      <group position={[0.46, 0, 0.18]} rotation={[0, -0.84, 0]} scale={0.44}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Sphere002_2.geometry}
          material={materials["Material.026"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m002"].geometry}
        material={materials["Material.028"]}
        position={[-0.43, 0.12, 0.29]}
        rotation={[Math.PI / 2, 0, -0.6]}
        scale={0.45}
      />
      <group position={[-0.09, -0.01, -0.11]} scale={[0.39, 0.18, 0.39]}>
        <mesh geometry={nodes.Circle043.geometry} material={materials.Leaves} />
        <mesh
          geometry={nodes.Circle043_1.geometry}
          material={materials.Trunk}
        />
      </group>
      <mesh
        geometry={nodes["Grass-s002"].geometry}
        material={materials["Material.003"]}
        position={[-0.16, 0.1, -0.15]}
        rotation={[1.47, 0.06, -2.17]}
        scale={0.33}
      />
      <group position={[-0.09, -0.2, 0.27]} scale={0.22}>
        <mesh
          geometry={nodes.Icosphere012.geometry}
          material={materials["Light-leave"]}
        />
        <mesh
          geometry={nodes.Icosphere012_1.geometry}
          material={materials["Light-leave-basic"]}
        />
      </group>
      <mesh
        geometry={nodes["Grass-m005"].geometry}
        material={materials["Material.001"]}
        position={[-0.47, 0.12, 0.09]}
        rotation={[Math.PI / 2, 0, -2.21]}
        scale={0.34}
      />
    </group>
  );
}

useGLTF.preload("/medium1disc.gltf");
