/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
//import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

//const loader = new GLTFLoader();

//const loadedData = await loader.loadAsync("/pinetreetest3.gltf");

export function Model(props) {
  const { nodes, materials } = useGLTF("/pinetreetest3.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FirTree3002.geometry} material={materials['Trees.003']} position={[18.12, 0, -13.64]} />
    </group>
  )
}

useGLTF.preload("/pinetreetest3.gltf");
