/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";

export function Tree(props: any) {
  const { nodes, materials } = useGLTF("pinetreetest3.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FirTree3002.geometry}
        material={materials["Trees.003"]}
        position={[18.12, 0, -13.64]}
      />
    </group>
  );
}

useGLTF.preload("pinetreetest3.gltf");
